# Generated by Django 5.0.6 on 2024-06-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_address_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
